import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  labSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Track Overview',
    },
    {
      type: 'doc',
      id: 'setup-guide',
      label: 'Setup Guide',
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      link: { type: 'doc', id: 'build/index' },
      items: [
        'build/00-setup',
        'build/01-scaffold-spa-portal',
        'build/02-dataverse-and-security',
        'build/03-web-api-integration',
      ],
    },
    {
      type: 'category',
      label: 'Integrate',
      collapsed: false,
      link: { type: 'doc', id: 'integrate/index' },
      items: [
        'integrate/00-setup',
        'integrate/04-pick-backend-pattern',
        'integrate/05-add-server-logic',
        'integrate/06-add-power-automate-flows',
        'integrate/07-add-ai-apis',
        'integrate/08-performance-test-deploy',
        'integrate/09-security-review',
      ],
    },
    {
      type: 'category',
      label: 'ALM',
      collapsed: false,
      link: { type: 'doc', id: 'alm/index' },
      items: [
        'alm/00-setup',
        'alm/10-source-control',
        'alm/11-solution-and-dependencies',
        'alm/12-branching-and-workflows',
        'alm/13-multi-env-promotion',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: { type: 'generated-index', slug: '/reference' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
};

export default sidebars;
