import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  labSidebar: [
    {
      type: 'doc',
      id: 'agentic-site-authoring',
      label: 'Track Overview',
    },
    {
      type: 'doc',
      id: 'setup-guide',
      label: 'Setup Guide',
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      link: { type: 'doc', id: 'build/index' },
      items: [
        'build/00-setup',
        'build/01-scaffold-spa-portal',
        'build/02-dataverse-and-security',
        'build/03-configure-authentication',
        'build/04-web-api-integration',
      ],
    },
    {
      type: 'category',
      label: 'Integrate',
      collapsed: false,
      link: { type: 'doc', id: 'integrate/index' },
      items: [
        'integrate/00-setup',
        'integrate/05-pick-backend-pattern',
        'integrate/06-add-server-logic',
        'integrate/07-add-power-automate-flows',
        'integrate/08-add-ai-apis',
        'integrate/09-performance-test-deploy',
        'integrate/10-security-review',
      ],
    },
    {
      type: 'category',
      label: 'ALM',
      collapsed: false,
      link: { type: 'doc', id: 'alm/index' },
      items: [
        'alm/00-setup',
        'alm/11-source-control',
        'alm/12-solution-and-dependencies',
        'alm/13-branching-and-workflows',
        'alm/14-multi-env-promotion',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: { type: 'generated-index', slug: '/reference' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
  reliableAlmSidebar: [
    {
      type: 'doc',
      id: 'reliable-alm/index',
      label: 'Reliable ALM overview',
    },
    'reliable-alm/00-setup',
    'reliable-alm/01-design-alm-blueprint',
    'reliable-alm/02-create-solution-and-source-control',
    'reliable-alm/03-branching-and-review-strategy',
    'reliable-alm/04-quality-security-gates',
    'reliable-alm/05-prepare-release-artifacts',
    'reliable-alm/06-set-up-ci-cd-and-pipelines',
    'reliable-alm/07-promote-and-operate',
  ],
};

export default sidebars;
