import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  labSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Track Overview',
    },
    {
      type: 'doc',
      id: 'setup-guide',
      label: 'Setup Guide',
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      link: { type: 'generated-index', slug: '/build' },
      items: [{ type: 'autogenerated', dirName: 'build' }],
    },
    {
      type: 'category',
      label: 'Integrate',
      collapsed: false,
      link: { type: 'generated-index', slug: '/integrate' },
      items: [{ type: 'autogenerated', dirName: 'integrate' }],
    },
    {
      type: 'category',
      label: 'ALM',
      collapsed: false,
      link: { type: 'generated-index', slug: '/alm' },
      items: [{ type: 'autogenerated', dirName: 'alm' }],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      link: { type: 'generated-index', slug: '/reference' },
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
};

export default sidebars;
